### ISSUE TITLE
Learn/Research about HTML

### ISSUE THREAD

**Issue by robynarnecke** [CS3398-Dione-LordFarquaadSquaad/CS3398-Dione-F2018#12]
Attempt to familiarize myself with HTML for use in our webpage.

**Comment by raa92** [comment]
I'll leave this here, there is a VERY handy app for learning to use HTML called *SoloLearn* : it has a course on how to create webpage files with HTML alone. We'll have to look further for research, though.

**Comment by robynarnecke** [comment]
Codecademy has a lesson on HTML as well, which I have started but haven't had a chance to finish.
